server:
    port: 8080
    http2:
      enabled: true


spring:
  main:
    web-application-type: reactive
  cloud:
      gateway:
          routes:
              - id: mysql_service
                uri: http://localhost:8082
                predicates:
                    - Path=/service1/**
                filters:
                  - RewritePath=/service1/(?<remaining>.*), /$\{remaining}
                  - PreserveHostHeader
              - id: mongo_service
                uri: http://localhost:8083
                predicates:
                    - Path=/service2/**
              - id: idm_service
                uri: no://op
                predicates:
                    - Path=/service3/**
                filters:
                  - GRPcCallsFilter

          default-filters:
            - StripPrefix=1
            - AddRequestHeader=proxied, true
            - OncePerRequestFilter
          filter:
            remove-hop-by-hop:
              headers: connection, keep-alive, x-frame-options
          httpclient:
            connect-timeout: 30000
            pool:
              max-connections: 2000

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG